target 'SPLManagedObjectContextSnapshot', :exclusive => true do
  pod "SPLManagedObjectContextSnapshot", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPLManagedObjectContextSnapshot", :path => "../"
  pod 'Expecta'
  pod 'SLCoreDataStack', '~> 0.6'
end
